sudo: required
services:
  - docker

language: go

go:
  - 1.5.3

script:
  #- make pull-images
  # uncomment to build fresh images
  #- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make images
  #- make push-images
  - make deps
  - make

